# Generated by Django 4.2 on 2026-02-07 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduled_appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(default='', max_length=60)),
                ('symptoms', models.CharField(default='', max_length=100)),
                ('email_id', models.CharField(default='', max_length=320)),
                ('mobile_number', models.CharField(max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('user_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('email_id', models.CharField(default='', max_length=320)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=20)),
                ('sex', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(default='', max_length=60)),
                ('family_doctor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('family_doctor_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('current_medication_list', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('emergency_first_name', models.CharField(default='', max_length=30)),
                ('emergency_last_name', models.CharField(default='', max_length=30)),
                ('emergency_relationship', models.CharField(default='', max_length=20)),
                ('emergency_mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('symptoms', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('appointment_date', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=320)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=10)),
                ('specialist_in', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
