# Generated by Django 4.2 on 2026-02-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_info',
            name='family_doctor_name',
        ),
        migrations.RemoveField(
            model_name='patient_info',
            name='family_doctor_phone',
        ),
    ]
