# Generated by Django 4.2 on 2026-04-28 16:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctorschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_info',
            name='appointment_date',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduled_appointments',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduled_appointments',
            name='time',
            field=models.TimeField(default=datetime.time(16, 44, 29, 425066)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduled_appointments',
            name='date',
            field=models.DateField(),
        ),
    ]
