# Generated by Django 4.2 on 2026-04-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_patient_info_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_duration', models.IntegerField(default=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='is_booked',
        ),
    ]
