# Generated by Django 4.2 on 2026-05-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_systemsetting_remove_doctorschedule_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
