# Generated by Django 4.2 on 2026-05-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_doctorschedule_is_booked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduled_appointments',
            options={'verbose_name_plural': 'Scheduled Appointments'},
        ),
        migrations.AddField(
            model_name='scheduled_appointments',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='scheduled_appointments',
            name='emergency_level',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Urgent'), (3, 'Critical')], default=1),
        ),
        migrations.AddField(
            model_name='scheduled_appointments',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
    ]
