# Generated by Django 4.2 on 2026-05-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_priority_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_infos',
            name='profile_description',
            field=models.TextField(blank=True, help_text='Short description of the doctor', null=True),
        ),
    ]
